In [1]:
import os 
import selenium 
from selenium import webdriver
import requests 
from webdriver_manager.chrome import ChromeDriverManager
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.webdriver.common.by import By
import pandas as pd

In [2]:
driver=webdriver.Chrome(ChromeDriverManager().install())
url='https://www.amazon.in/s?k={q}&crid=IP55FNTR72B&sprefix=laptop%2Caps%2C267&ref=nb_sb_noss_1'
item=input("Enter What you  want to search => ")
driver.get(url.format(q=item))
products = driver.find_elements(By.XPATH,'//div[@data-component-type="s-search-result"]')

product_name = []
product_price = []
product_reviews = []
final_list = []

C:\Users\HP\AppData\Local\Temp\ipykernel_5556\1331795910.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(ChromeDriverManager().install())

Enter What you  want to search => mobile

In [3]:
for product in products: 
  
    pnames =product.find_elements(By.XPATH,".//span[@class='a-size-medium a-color-base a-text-normal']")
    for name in pnames:
        product_name.append(name.text)
        
    try:
        if len(product.find_elements(By.XPATH,".//span[@class='a-price-whole']"))>0:
            pprices= product.find_elements(By.XPATH,".//span[@class='a-price-whole']")
            for price in pprices:
                # print('the lenght is ===>',len(price.text))
                product_price.append(price.text)
        else:
            product_price.append("0")
    except:
        pass
    # reviews = laptop.find_elements(By.XPATH,".//span[@class='a-size-base s-underline-text']")
    
    try:
        if len(product.find_elements(By.XPATH,".//span[@class='a-size-base s-underline-text']"))>0:
            previews = product.find_elements(By.XPATH,".//span[@class='a-size-base s-underline-text']")
            for review in previews:
                # print('the length is===>', len(review.text), review.text)
                product_reviews.append(review.text)
        else:
            no_reviews.append("0")
    except:
        pass
        
print('no of',item,'=>',len(product_name))
print('no of prices==>',len(product_price))
print('no of reviews==>',len(product_reviews))


final_list = [item for sublist in zip(product_name, product_price,product_reviews) for item in sublist]

no of mobile => 22
no of prices==> 22
no of reviews==> 21

In [4]:
data = pd. DataFrame()
data['name']= product_name
data['price']= product_price

data.head(22)

                                                 name   price
0   Samsung Galaxy M53 5G (Mystique Green, 6GB, 12...  21,999
1   Samsung Galaxy S20 FE 5G (Cloud Mint, 8GB RAM,...  29,990
2   Redmi 9 Activ (Coral Green, 4GB RAM, 64GB Stor...   8,099
3   Smartphone Reno7 5G (Startrails Blue, 8GB RAM,...       0
4   Redmi 9A Sport (Coral Green, 2GB RAM, 32GB Sto...   6,999
5   OPPO A31 (Mystery Black, 6GB RAM, 128GB Storag...  11,990
6   OPPO A74 5G (Fantastic Purple,6GB RAM,128GB St...  14,990
7   realme narzo 50A Prime (Flash Black, 4GB RAM+1...   9,499
8   OPPO A15s (Rainbow Silver, 4GB RAM, 64GB Stora...   9,990
9   Redmi 9 Activ (Metallic Purple, 4GB RAM, 64GB ...   8,099
10  Samsung Galaxy M13 (Aqua Green, 4GB, 64GB Stor...   9,499
11  Redmi Note 11 (Space Black, 6GB RAM, 64GB Stor...  13,999
12  Redmi 9A Sport (Metallic Blue, 2GB RAM, 32GB S...   6,999
13  Redmi 10 Prime (Phantom Black 4GB RAM 64GB | H...  10,999
14  realme narzo 50i Prime (Dark Blue 4GB RAM+64GB...   7,777
15  Redmi 9 Activ (Coral Green, 6GB RAM, 128GB Sto...  10,499
16  Redmi 9A Sport (Carbon Black, 2GB RAM, 32GB St...   6,999
17  Redmi Note 11T 5G (Matte Black, 8GB RAM, 128GB...  16,999
18  Samsung Galaxy M33 5G (Emerald Brown, 8GB, 128...  16,999
19  realme narzo 50i (Carbon Black, 4GB RAM+64GB S...   8,499
20  Redmi Note 11T 5G (Aquamarine Blue, 6GB RAM, 1...  15,999
21  iQOO Z6 Lite 5G (Stellar Green, 6GB RAM, 128GB...  15,499

In [5]:
data.to_csv('amazonp.csv', index=False)